package ai

import("bytes";"context";"encoding/json";"fmt";"io";"net/http";"strings";"time";"github.com/sagarbagwe/jobapply-ai/backend/internal/model")
type Gemini struct{apiKey,model string; client *http.Client}
func NewGemini(key,modelName string)*Gemini{return &Gemini{apiKey:key,model:modelName,client:&http.Client{Timeout:25*time.Second}}}
type request struct{Contents []content `json:"contents"`; GenerationConfig config `json:"generationConfig"`};type content struct{Parts []part `json:"parts"`};type part struct{Text string `json:"text"`};type config struct{ResponseMIMEType string `json:"responseMimeType"`};type response struct{Candidates []struct{Content content `json:"content"`} `json:"candidates"`}
func(g *Gemini)generate(ctx context.Context,prompt string,out any)error{if g.apiKey==""{return ErrNotConfigured};body,_:=json.Marshal(request{Contents:[]content{{Parts:[]part{{Text:prompt}}}},GenerationConfig:config{ResponseMIMEType:"application/json"}});u:=fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s",g.model,g.apiKey);req,_:=http.NewRequestWithContext(ctx,http.MethodPost,u,bytes.NewReader(body));req.Header.Set("Content-Type","application/json");res,err:=g.client.Do(req);if err!=nil{return err};defer res.Body.Close();if res.StatusCode/100!=2{b,_:=io.ReadAll(io.LimitReader(res.Body,2048));return fmt.Errorf("gemini: status %d: %s",res.StatusCode,string(b))};var r response;if err=json.NewDecoder(res.Body).Decode(&r);err!=nil{return err};if len(r.Candidates)==0||len(r.Candidates[0].Content.Parts)==0{return fmt.Errorf("gemini: empty response")};return json.Unmarshal([]byte(strings.TrimSpace(r.Candidates[0].Content.Parts[0].Text)),out)}
func(g *Gemini)Match(ctx context.Context,in model.MatchRequest)(out model.MatchResult,err error){b,_:=json.Marshal(in);err=g.generate(ctx,"Return strict JSON for an internal job relevance score. Never imply interview probability. Do not invent facts. Fields: match_score 0-100, matched_skills, missing_skills, experience_match, location_match, recommendation apply|review|ignore, rationale. Input: "+string(b),&out);return}
func(g *Gemini)Answer(ctx context.Context,in model.AnswerRequest)(out model.AnswerResult,err error){b,_:=json.Marshal(in);err=g.generate(ctx,"Draft a concise truthful answer using only supplied facts. Never invent employment, education, achievements, salary, projects, certification, or authorization. Return JSON: answer, requires_review=true. Input: "+string(b),&out);out.RequiresReview=true;return}
